### ISSUE TITLE
Give the interfaces and classes a proper order

### ISSUE THREAD

**Issue by feidens** [upbcuk/upb.crypto.craco#11]
Currently the interfaces are partially sorted into the special global interfaces package `de.upb.crypto.craco.interfaces` and others can be found in under their respective parent, e.g. `de.upb.crypto.craco.accumulators.interfaces`.

* Fix this by following the second approach.
* Put common interface unter package common

For the classes the problem should be further discussed, but for example up to now the `abe` package not places under the `enc` package.

**Comment by rheitjoh** [comment]
Do the proxy interfaces belong into common? They are currently only used by the ElGamal KEM.

**Comment by JanBobolz** [comment]
"Common", I think, is supposed to be for things like `PlainText`, which is used for signatures and encryption. 

The proxy reencryption stuff doesn't seem as general. 

Overall: we're not 100% on what this should look like. Come up with any sane structure @rheitjoh :)

**Comment by feidens** [comment]
@rheitjoh any update on that?

**Comment by rheitjoh** [comment]
If I recall correctly, the corresponding craco branch should basically be finished, but we put it on hold because of the math rewrite.

**Comment by feidens** [comment]
Can you mention the branch here? Than we have some record of it.

**Comment by rheitjoh** [comment]
The commit above also links to it, but its [this one](https://github.com/upbcuk/upb.crypto.craco/compare/interface-order)

**Comment by feidens** [comment]
It is the commit 0a4acc7 (for the record).
Could you write down your plan here? Therefore, we know what we wanted to do even if we have to scrap the commit in the future.

**Comment by rheitjoh** [comment]
To summarize what I did:
Basically moved everything from the top-level `interfaces` folder to more specific interfaces folders, e.g. ABE-related interfaces can now be found under abe/interfaces. Common interfaces are now in `common/interfaces`.

**Comment by rheitjoh** [comment]
Would like to merge this after the `lazy` branch in #22.

**Comment by rheitjoh** [comment]
Fixed by #20
