### ISSUE TITLE
Remove performance tests

### ISSUE THREAD

**Issue by JanBobolz** [upbcuk/upb.crypto.craco#31]
To not waste energy for (travis) builds, I'd like to have long-running performance tests not be run during `./gradlew test`.

There are several ways to go about this

1. move performance tests to another package (e.g., benchmark package)
2. delete performance tests
3. exclude performance tests from `./gradlew test` runs.

I don't have strong feelings which option to take.

**Comment by JanBobolz** [comment]
(I'm aware only of the `SignatureScheme` tests that take a long time)

**Comment by rheitjoh** [comment]
I removed the performance benchmarking from the signature tests with #33 by enabling the debug pairing usage in the SPSEQ tests. Benchmarks should be part of the Benchmark project as you mentioned and be separated from unit tests.
